name: Master Release

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
    # test:

    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v2
            
            - name: Create .env.local file
              run: echo "${{ secrets.ENV_PRODUCTION }}" > .env.local
            - run: bun i --force
            - run: bun run build